---

- name: Ensure etcd dir is created
  file:
    path: /etc/etcd/
    recurse: yes
    state: directory
    owner: root
    group: root
  become: yes

- name: Copy TLS certificates
  copy:
    src: "{{ playbook_dir }}/../cert-authority/{{ item }}"
    dest: /etc/etcd/
    owner: root
    group: root
    mode: 0644
  with_items:
    - ca.pem
    - kubernetes-key.pem
    - kubernetes.pem
  become: yes

- name: Download and unzip etcd binaries
  unarchive:
    src: https://github.com/coreos/etcd/releases/download/v3.0.10/etcd-v3.0.10-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move etcd binaries to bin
  copy:
    src: "{{ item }}"
    dest: /usr/bin
    remote_src: yes
    mode: 0755
  with_items:
    - /tmp/etcd-v3.0.10-linux-amd64/etcd
    - /tmp/etcd-v3.0.10-linux-amd64/etcdctl
  become: yes

- name: Copy etcd systemd unit template
  template:
    src: templates/etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Enable etcd systemd unit
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: etcd
  become: yes
